// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDef9XjRcG2WtQFFK4wEOtS6JthL8gsKgc',
    appId: '1:663715614972:web:1814e14740fc9c4daf0779',
    messagingSenderId: '663715614972',
    projectId: 'equisplit-sxpz23',
    authDomain: 'equisplit-sxpz23.firebaseapp.com',
    storageBucket: 'equisplit-sxpz23.firebasestorage.app',
    measurementId: 'G-4Z25FJ5YXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvvqdtlgqN6uZvpbUFyuUHu3f0uUShlQc',
    appId: '1:663715614972:android:328e0fc57e11acf3af0779',
    messagingSenderId: '663715614972',
    projectId: 'equisplit-sxpz23',
    storageBucket: 'equisplit-sxpz23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8TMyOAzR9fvuK1lKvjsf01wmWCfHD-eE',
    appId: '1:663715614972:ios:505a29b5168fba21af0779',
    messagingSenderId: '663715614972',
    projectId: 'equisplit-sxpz23',
    storageBucket: 'equisplit-sxpz23.firebasestorage.app',
    iosBundleId: 'dev.sxpz23.equisplit',
  );
}
